---
title: "main analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(ggplot2)
library(dplyr)
df = read.csv('data_income_edited.csv',stringsAsFactors=FALSE)
```

```{r}
g <- c('white','black')
df_gender <- df %>% filter(df$gender == 'Male' | df$gender == 'Female') 
mosaic(depressed ~ gender, df_gender, direction =c('v','h'),gp = gpar(fill = g), main = 'Depressed vs Gender')
```

```{r}
library(vcd)
library(grid)
g <- c('white','black')
mosaic(depressed ~ sexuallity, df, direction =c('v','h'),gp = gpar(fill = g), main = 'Depressed vs Sexuality', rot_labels=c(30,0,0,90),gp_labels=(gpar(fontsize=10)))

```
```{r}
mosaic(attempt_suicide ~ sexuallity, df, direction =c('v','h'),gp = gpar(fill = g), main = 'Suicide Attempt vs Sexuality', rot_labels=c(30,0,0,90),gp_labels=(gpar(fontsize=10)))
```
```{r}
mosaic(depressed ~ social_fear, df, direction =c('v','h'),gp = gpar(fill = g), main = 'Depressed vs Social Fear')
```
```{r}
frdep <- df %>% select(friends,depressed) %>% filter(friends <= 50) %>% filter(friends != 0) 
ggplot(frdep,aes(x=friends,color=depressed,fill=depressed)) + geom_density(alpha = 0.1) + ggtitle('Density plot for Number of friends vs Depressed')
```
```{r}
frddep <- df %>% select(friends, depressed)  %>% filter(friends <= 100) %>% filter(friends != 0) 
frddep <- frddep[frddep$friends <= 20,]
ggplot(frddep, aes(x=depressed, y=friends)) + geom_boxplot() + ggtitle('Box plot for Number of friends vs Depressed')
```
```{r}

```


```{r}
df$friends.f <- as.factor(
  sapply(df$friends, function(x){
    ifelse(x > 50, x <- ">50",
    ifelse(x > 30 & x <= 50, x <- "30-50",
    ifelse(x > 10 & x <= 30, x <- "10-30",
    ifelse(x > 0 & x <= 10, x <- "1-10",
    x <- "no friends"))))
  })
)
positions <- c('no friends','1-10', '10-30', '30-50', '>50')

ggplot(data = df, aes(x = friends.f, fill = social_fear)) + 
  ggtitle("Number of friends + Social Fear") + 
  labs(x = "Number of friends", y = "percentage") +
  geom_bar(alpha = 0.7
           , position="fill"
           , col = 'black') + 
  scale_fill_manual(values=c("white", "black")) + scale_x_discrete(limits = positions)



```
```{r}
ggplot(data = df, aes(x = friends.f, fill = attempt_suicide)) + 
  ggtitle("Number of friends + Sucide Attempt") + 
  labs(x = "Number of friends", y = "percentage") +
  geom_bar(alpha = 0.7
           , position="fill"
           , col = 'black') + 
  scale_fill_manual(values=c("white", "black")) + scale_x_discrete(limits = positions)

```
```{r}
df$employment[df$employment == 'Out of work but not currently looking for work'] <- 'Not looking for work'
df$employment[df$employment == 'Out of work and looking for work'] <- 'Looking for work'

p1 <- c('Military','A student','Employed for wages','Self-employed','A homemaker','Looking for work','Not looking for work','Unable to work','Retired')
ggplot(data = df, aes(x = employment, fill = depressed)) + 
  ggtitle("Employment + Depressed") + 
  labs(x = "Employment", y = "Percentage") +
  geom_bar(alpha = 0.7
           , position="fill"
           , col = 'black') + 
  scale_fill_manual(values=c("white", "black")) +scale_x_discrete(limits = p1)+coord_flip() 
```

```{r}
p2 <- c('Retired','Military','A homemaker','Employed for wages','A student','Not looking for work','Self-employed','Looking for work','Unable to work')
ggplot(data = df, aes(x = employment, fill = attempt_suicide)) + 
  ggtitle("Employment + Suicide attempt") + 
  labs(x = "Employment", y = "Percentage") +
  geom_bar(alpha = 0.7
           , position="fill"
           , col = 'black') + 
  scale_fill_manual(values=c("white", "black")) +scale_x_discrete(limits = p2)+coord_flip() 
```
```{r}
ggplot(df, aes(income, color=depressed,fill=depressed)) + geom_density(alpha=0.1) + ggtitle('Density plot for Income vs Depressed')
```
```{r}
ggplot(df,aes(depressed, income))+geom_boxplot()+ ggtitle('Boxplot for Income vs Depressed')
```

```{r}
library(tidyverse)
ggplot(df, aes(fct_reorder(edu_level, income, median), income)) + 
  geom_boxplot() + xlab('education level') + coord_flip() + 
  ggtitle('Income by education level')
```

